INSERT INTO property (pid, llid, house_number, street) VALUES (1, 1, '3408', 'Parkview Avenue');
INSERT INTO property (pid, llid, house_number, street) VALUES (2, 1, '430', 'Atwood Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (3, 2, '3624', 'Bates Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (4, 2, '326', 'South Bouquet Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (5, 2, '3353', 'Dawson Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (6, 2, '402', 'Atwood Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (7, 3, '382', 'South Bouquet Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (8, 3, '3817', 'Dawson Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (9, 3, '414', 'Neville Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (10, 4, '101', 'Atwood Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (11, 4, '3432', 'Ward Street');
INSERT INTO property (pid, llid, house_number, street) VALUES (12, 6, '214', 'Dunseith Street');